#!/usr/bin/with-contenv bash
# shellcheck shell=bash

HORA_BLOQUEIA=$(date --date=$BLOCK +"%s")
HORA_LIBERA=$(date --date=$UNBLOCK +"%s")
AGORA=$(date +%s)

echo $BLOCK +" em segundos "+  $HORA_BLOQUEIA

pihole --regex -d '.*'

if [[ "$AGORA" > "$HORA_BLOQUEIA" ]] || [[ "$AGORA" < "$HORA_LIBERA" ]]; then
  pihole --regex '.*'
fi

sleep 360
