#!/usr/bin/with-contenv bash
# shellcheck shell=bash

HORA_BLOQUEIA=$(date --date="16:47" +"%s")
HORA_LIBERA=$(date --date="08:00" +"%s")
AGORA=$(date +%s)

echo $HORA_BLOQUEIA
echo $AGORA

if [[ "$AGORA" > "$HORA_BLOQUEIA" ]] || [[ "$AGORA" < "$HORA_LIBERA" ]]; then
  echo "bloqueia"
else
  echo "desbloqueia"
fi

sleep 360
