FROM lscr.io/linuxserver/syncthing

COPY default-config.xml /config/config.xml
COPY cont-init.d/ /etc/cont-init.d/

ENV SYNC_ID_PRINCIPAL NJXQYKR-QKAB5H6-HPVA3J6-3RFWNEV-DNRODEM-DLUKMVO-MHVRVB5-CE6ONAN
ENV SYNC_NOME_PRINCIPAL Tecendo Redes
ENV SYNC_ID_ACERVO seuhx-ilp3c
ENV SYNC_NOME_ACERVO Acervo Comunitario
